# Generated by Django 2.1.2 on 2018-10-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('mac_address', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('signal_strength', models.IntegerField()),
                ('age', models.IntegerField(default=0)),
                ('channel', models.IntegerField()),
                ('signal_to_noise_ratio', models.IntegerField()),
                ('ssid', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac_address', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('vendor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(default='Pi Zero', max_length=30)),
                ('mac_address', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='discovered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Node'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='discovered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Node'),
        ),
    ]
