# Generated by Django 2.1.2 on 2018-10-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
